Remove redundant self at line 79, 82, 89 from spiders.py (#218)
In spiders.py, got three redundant words "self" in line 79, 82, 89 separately. Cause an error AttributeError: 'MySpider' object has no attribute 'settings'.